apiVersion: 1

datasources:
  - name: VictoriaMetrics
    type: prometheus
    access: proxy
    url: http://victoriametrics:8428
    basicAuth: true
    basicAuthUser: ${VM_AUTH_USER}
    secureJsonData:
      basicAuthPassword: ${VM_AUTH_PASS}
    isDefault: true
    editable: false
